### ISSUE TITLE
Velvet tx has 3 outputs

### ISSUE THREAD

**Issue by gtklocker** [gtklocker/bcash-interlinker#10]
The 3 outputs are OP_RETURN, dust to the tagged SPV address, and change.

Could we do away with the dust altogether while passing through the SPV filter for the tagged address? @dionyziz

**Comment by dionyziz** [comment]
Transactions with an OP_RETURN output cannot have other outputs. We must devise another way.

**Comment by gtklocker** [comment]
Why not? [This](https://www.blocktrail.com/tBCC/tx/6ae0925ceeb74790ce5017328d5955b43129dfdbec16e5e312dc6285b68832bb) is a recent interlink tx and it looks ok.

**Comment by gtklocker** [comment]
Of course it's marked as "containing dust" and I don't know what implications this may have on relaying. But it's been OK on testnet at least.

**Comment by dionyziz** [comment]
Seems like you're right, I was confused. Can you check if an OP_RETURN output with a specific constant is captured by the SPV filter in which this constant has been added? I would expect yes.

**Comment by gtklocker** [comment]
Spent the day getting a bcash SPV tx monitor prototype up and running: https://gist.github.com/gtklocker/4b9323c9120d505dda7d97f31b5b81de

Should serve for our tests.
